name: ecokit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f0b25'
    - '#532b34'
    - '#6a4745'
    - '#81092c'
    - '#8d7670'
  brandStrength: 0.9036931844893843
  lightness: 0.7148705362342298
  saturation: 0.15655433386564255
  rhythmicContrast: 0.611383555456996
purpose: []
